export type SlotEmoji = {
  emoji: string
  label: string
  /** Extra search terms — the label alone often isn't what people type. */
  keywords?: string[]
}

export type SlotEmojiGroup = {
  name: string
  emojis: SlotEmoji[]
}

/** Compact entry: [emoji, label, ...keywords] — keeps this file readable. */
type Row = [string, string, ...string[]]

function group(name: string, rows: Row[]): SlotEmojiGroup {
  return {
    name,
    emojis: rows.map(([emoji, label, ...keywords]) => ({
      emoji,
      label,
      keywords: keywords.length ? keywords : undefined,
    })),
  }
}

export const SLOT_EMOJI_GROUPS: SlotEmojiGroup[] = [
  group('Food', [
    ['🍽', 'Dining', 'food', 'restaurant', 'dinner', 'lunch', 'meal', 'eat'],
    ['🍳', 'Breakfast', 'eggs', 'brunch', 'morning'],
    ['🥐', 'Croissant', 'bakery', 'pastry', 'french'],
    ['🥞', 'Pancakes', 'brunch'],
    ['🧇', 'Waffles', 'brunch'],
    ['🥯', 'Bagel', 'deli'],
    ['🍞', 'Bread', 'bakery'],
    ['🥖', 'Baguette', 'bread', 'bakery', 'french'],
    ['🥨', 'Pretzel', 'german', 'snack'],
    ['🧀', 'Cheese', 'fromage', 'tasting'],
    ['🥚', 'Eggs', 'breakfast'],
    ['🧈', 'Butter', 'breakfast'],
    ['🥜', 'Nuts', 'snack'],
    ['🍕', 'Pizza', 'italian', 'slice'],
    ['🍔', 'Burger', 'american', 'fast food'],
    ['🌭', 'Hot dog', 'street food'],
    ['🥪', 'Sandwich', 'deli', 'lunch'],
    ['🌮', 'Tacos', 'mexican', 'street food'],
    ['🌯', 'Burrito', 'mexican', 'wrap'],
    ['🫔', 'Tamale', 'mexican'],
    ['🥙', 'Kebab', 'gyro', 'pita', 'wrap'],
    ['🧆', 'Falafel', 'middle eastern', 'vegetarian'],
    ['🥘', 'Paella', 'spanish', 'stew'],
    ['🫕', 'Fondue', 'stew', 'swiss', 'cheese'],
    ['🍲', 'Hot pot', 'soup', 'stew'],
    ['🥣', 'Soup', 'bowl', 'broth'],
    ['🍜', 'Noodles', 'ramen', 'pho', 'asian', 'soup'],
    ['🍝', 'Pasta', 'italian', 'spaghetti'],
    ['🍛', 'Curry', 'indian', 'thai', 'rice'],
    ['🍚', 'Rice', 'asian'],
    ['🍙', 'Onigiri', 'japanese', 'rice ball'],
    ['🍢', 'Oden', 'skewers', 'japanese', 'street food'],
    ['🍡', 'Dango', 'japanese', 'sweet', 'skewer'],
    ['🍥', 'Fish cake', 'japanese', 'ramen'],
    ['🍣', 'Sushi', 'japanese', 'sashimi', 'fish'],
    ['🍤', 'Tempura', 'japanese', 'fried', 'prawn'],
    ['🍱', 'Bento', 'japanese', 'lunch box'],
    ['🥟', 'Dumplings', 'dim sum', 'chinese', 'gyoza'],
    ['🥠', 'Fortune cookie', 'chinese', 'dessert'],
    ['🍘', 'Rice cracker', 'snack', 'japanese'],
    ['🦐', 'Shrimp', 'seafood', 'prawn'],
    ['🦞', 'Lobster', 'seafood'],
    ['🦀', 'Crab', 'seafood'],
    ['🦑', 'Squid', 'seafood', 'calamari'],
    ['🦪', 'Oysters', 'seafood', 'raw bar'],
    ['🐟', 'Fish', 'seafood'],
    ['🥩', 'Steak', 'meat', 'grill', 'steakhouse'],
    ['🍖', 'BBQ', 'grill', 'barbecue', 'meat', 'ribs'],
    ['🍗', 'Chicken', 'poultry', 'meat'],
    ['🥓', 'Bacon', 'breakfast', 'meat'],
    ['🌽', 'Corn', 'street food', 'grill'],
    ['🥗', 'Salad', 'healthy', 'vegetarian', 'greens'],
    ['🥑', 'Avocado', 'healthy', 'brunch'],
    ['🍅', 'Tomato', 'fresh', 'market'],
    ['🥕', 'Vegetables', 'veg', 'market', 'healthy'],
    ['🍄', 'Mushrooms', 'forage', 'market'],
    ['🫒', 'Olives', 'tapas', 'mediterranean'],
    ['🍉', 'Fruit', 'watermelon', 'fresh', 'healthy'],
    ['🍓', 'Berries', 'strawberry', 'fruit'],
    ['🍊', 'Citrus', 'orange', 'fruit'],
    ['🍋', 'Lemon', 'citrus', 'fruit'],
    ['🍇', 'Grapes', 'vineyard', 'fruit', 'wine'],
    ['🍍', 'Pineapple', 'tropical', 'fruit'],
    ['🥭', 'Mango', 'tropical', 'fruit'],
    ['🍌', 'Banana', 'fruit', 'tropical'],
    ['🥥', 'Coconut', 'tropical', 'beach'],
    ['🌶', 'Spicy', 'chili', 'hot', 'pepper'],
    ['🧂', 'Seasoning', 'salt', 'condiment'],
    ['🍰', 'Cake', 'dessert', 'sweet', 'birthday'],
    ['🎂', 'Birthday cake', 'celebration', 'dessert'],
    ['🧁', 'Cupcake', 'dessert', 'bakery', 'sweet'],
    ['🥧', 'Pie', 'dessert', 'sweet'],
    ['🍮', 'Custard', 'flan', 'dessert', 'pastel de nata'],
    ['🍩', 'Donut', 'dessert', 'sweet', 'bakery'],
    ['🍪', 'Cookie', 'dessert', 'sweet'],
    ['🍫', 'Chocolate', 'dessert', 'sweet'],
    ['🍬', 'Sweets', 'candy', 'confectionery'],
    ['🍭', 'Lollipop', 'candy', 'sweet'],
    ['🍦', 'Ice cream', 'gelato', 'dessert', 'sweet'],
    ['🍨', 'Sundae', 'ice cream', 'dessert'],
    ['🍧', 'Shaved ice', 'dessert', 'sweet'],
    ['🍯', 'Honey', 'sweet', 'market'],
    ['🥡', 'Takeout', 'to go', 'delivery'],
    ['🧺', 'Picnic', 'basket', 'outdoor', 'park'],
    ['🍴', 'Cutlery', 'eat', 'restaurant'],
    ['👨‍🍳', 'Chef', 'cooking class', 'kitchen', 'tasting menu'],
  ]),

  group('Drink', [
    ['☕', 'Coffee', 'cafe', 'espresso', 'latte', 'morning'],
    ['🫖', 'Teapot', 'tea', 'afternoon tea'],
    ['🍵', 'Tea', 'matcha', 'teahouse'],
    ['🧋', 'Boba', 'bubble tea', 'milk tea'],
    ['🥤', 'Soft drink', 'soda', 'juice', 'smoothie'],
    ['🧃', 'Juice', 'drink', 'fresh'],
    ['🥛', 'Milk', 'dairy', 'drink'],
    ['🧊', 'Iced', 'ice', 'cold drink'],
    ['🍷', 'Wine', 'vineyard', 'winery', 'tasting', 'bar'],
    ['🍇', 'Vineyard', 'wine', 'grapes', 'tasting'],
    ['🥂', 'Champagne', 'toast', 'celebrate', 'prosecco', 'bubbly'],
    ['🍸', 'Cocktails', 'martini', 'bar', 'drinks', 'happy hour'],
    ['🍹', 'Tropical drink', 'cocktail', 'beach', 'tiki'],
    ['🍺', 'Beer', 'pub', 'brewery', 'bar', 'pint'],
    ['🍻', 'Cheers', 'beers', 'pub', 'group', 'toast'],
    ['🥃', 'Whiskey', 'bourbon', 'scotch', 'nightcap', 'bar'],
    ['🍾', 'Bottle service', 'champagne', 'celebrate'],
    ['🍶', 'Sake', 'japanese', 'drink'],
    ['🧉', 'Maté', 'drink', 'south america'],
    ['🫗', 'Pour', 'drink', 'tasting'],
  ]),

  group('Nightlife', [
    ['🎉', 'Party', 'celebrate', 'night out'],
    ['🪩', 'Club', 'disco', 'dance', 'nightclub'],
    ['💃', 'Dancing', 'salsa', 'club', 'night'],
    ['🕺', 'Dance floor', 'club', 'night'],
    ['🎤', 'Karaoke', 'singing', 'live music', 'concert'],
    ['🎧', 'DJ set', 'music', 'club', 'headphones'],
    ['🎹', 'Piano bar', 'music', 'lounge'],
    ['🎰', 'Casino', 'gambling', 'slots', 'vegas'],
    ['🃏', 'Cards', 'poker', 'casino', 'games'],
    ['🎆', 'Fireworks', 'celebration', 'night', 'festival'],
    ['🌃', 'City night', 'skyline', 'evening', 'nightlife'],
    ['🍸', 'Late drinks', 'bar', 'cocktail', 'nightcap'],
  ]),

  group('Culture', [
    ['🎭', 'Theatre', 'play', 'show', 'drama', 'broadway'],
    ['🎨', 'Art', 'gallery', 'museum', 'painting', 'exhibit'],
    ['🖼', 'Gallery', 'art', 'museum', 'exhibit', 'painting'],
    ['🏛', 'Museum', 'ruins', 'gallery', 'history', 'classical'],
    ['🗿', 'Antiquities', 'ruins', 'archaeology', 'statue'],
    ['🎬', 'Cinema', 'movie', 'film', 'theater'],
    ['🍿', 'Movie night', 'cinema', 'film', 'popcorn'],
    ['🎵', 'Music', 'concert', 'gig', 'song'],
    ['🎼', 'Classical', 'orchestra', 'symphony', 'opera'],
    ['🎻', 'Orchestra', 'violin', 'classical', 'symphony'],
    ['🎸', 'Live music', 'guitar', 'band', 'rock', 'gig'],
    ['🎷', 'Jazz', 'saxophone', 'live music', 'blues'],
    ['🎺', 'Brass', 'trumpet', 'band', 'parade'],
    ['🪗', 'Folk music', 'accordion', 'fado', 'traditional'],
    ['🥁', 'Drums', 'music', 'percussion', 'band'],
    ['📚', 'Bookshop', 'library', 'books', 'reading'],
    ['📖', 'Reading', 'book', 'quiet', 'downtime'],
    ['🎪', 'Circus', 'show', 'festival', 'tent'],
    ['🎡', 'Fairground', 'ferris wheel', 'carnival', 'amusement'],
    ['🎢', 'Rollercoaster', 'theme park', 'amusement', 'rides'],
    ['🎠', 'Carousel', 'fair', 'amusement', 'kids'],
    ['🖌', 'Workshop', 'class', 'craft', 'paint', 'lesson'],
    ['🧵', 'Craft', 'textile', 'workshop', 'artisan'],
    ['🏺', 'Pottery', 'ceramics', 'craft', 'artisan'],
    ['📸', 'Photography', 'photos', 'camera', 'shoot'],
    ['🎥', 'Filming', 'video', 'camera'],
    ['🗞', 'Local news', 'newspaper', 'reading'],
    ['🪅', 'Festival', 'celebration', 'party', 'parade'],
  ]),

  group('Shopping', [
    ['🛍', 'Shopping', 'shops', 'retail', 'boutique', 'mall'],
    ['🛒', 'Groceries', 'supermarket', 'shopping', 'market'],
    ['🧺', 'Farmers market', 'market', 'produce', 'local'],
    ['💐', 'Flower market', 'flowers', 'bouquet', 'market'],
    ['🕯', 'Home goods', 'candle', 'shop', 'decor'],
    ['💎', 'Jewellery', 'jewelry', 'shopping', 'luxury'],
    ['⌚', 'Watches', 'shopping', 'luxury'],
    ['👗', 'Boutique', 'clothes', 'fashion', 'shopping'],
    ['👕', 'Clothes', 'fashion', 'shopping'],
    ['👟', 'Sneakers', 'shoes', 'shopping'],
    ['👜', 'Bags', 'handbag', 'shopping', 'leather'],
    ['🕶', 'Sunglasses', 'shopping', 'accessories'],
    ['🧳', 'Souvenirs', 'gifts', 'luggage', 'shopping'],
    ['🎁', 'Gifts', 'present', 'souvenir', 'shopping'],
    ['📿', 'Antiques', 'vintage', 'market', 'flea'],
    ['🖼', 'Art shopping', 'print', 'gallery', 'poster'],
    ['🍾', 'Bottle shop', 'wine', 'off licence', 'shopping'],
  ]),

  group('Outdoors', [
    ['🏖', 'Beach', 'sea', 'sand', 'coast', 'swim'],
    ['🏝', 'Island', 'tropical', 'beach', 'getaway'],
    ['🌊', 'Coast', 'ocean', 'sea', 'waves'],
    ['🏔', 'Mountain', 'alps', 'peak', 'summit'],
    ['⛰', 'Hills', 'mountain', 'viewpoint', 'trek'],
    ['🥾', 'Hiking', 'trek', 'trail', 'walk', 'boots'],
    ['🧗', 'Climbing', 'bouldering', 'rock', 'via ferrata'],
    ['🚴', 'Cycling', 'bike', 'ride', 'tour'],
    ['🏊', 'Swimming', 'pool', 'swim', 'sea'],
    ['🤽', 'Water polo', 'pool', 'swim'],
    ['🏄', 'Surfing', 'waves', 'surf', 'beach'],
    ['🪝', 'Angling', 'fishing', 'hook'],
    ['🤿', 'Diving', 'snorkel', 'scuba', 'reef'],
    ['🛶', 'Canoe', 'kayak', 'paddle', 'river'],
    ['🚣', 'Kayak', 'rowing', 'paddle', 'boat'],
    ['⛵', 'Sailing', 'boat', 'yacht', 'cruise'],
    ['🎣', 'Fishing', 'angling', 'lake', 'boat'],
    ['⛷', 'Skiing', 'snow', 'slopes', 'alpine', 'winter'],
    ['🏂', 'Snowboarding', 'snow', 'slopes', 'winter'],
    ['🛷', 'Sledding', 'snow', 'winter', 'toboggan'],
    ['⛸', 'Ice skating', 'rink', 'winter'],
    ['🏇', 'Horse riding', 'equestrian', 'ranch', 'trail'],
    ['🎿', 'Ski gear', 'snow', 'winter', 'rental'],
    ['🪂', 'Paragliding', 'skydive', 'flying', 'adventure'],
    ['🎈', 'Hot air balloon', 'balloon', 'ride', 'sunrise'],
    ['⛺', 'Camping', 'tent', 'outdoors', 'campsite'],
    ['🔥', 'Campfire', 'bonfire', 'fire', 'evening'],
    ['🧭', 'Exploring', 'compass', 'wander', 'adventure'],
    ['🗺', 'Tour', 'map', 'guide', 'sightseeing', 'walking tour'],
    ['🔭', 'Observatory', 'telescope', 'stars', 'viewpoint'],
    ['🔦', 'Caving', 'torch', 'cave', 'underground'],
    ['🪁', 'Kite flying', 'beach', 'park', 'wind'],
  ]),

  group('Sport', [
    ['⚽', 'Football', 'soccer', 'match', 'game', 'stadium'],
    ['🏀', 'Basketball', 'game', 'nba', 'match'],
    ['🏈', 'American football', 'nfl', 'game'],
    ['⚾', 'Baseball', 'game', 'mlb', 'ballpark'],
    ['🥎', 'Softball', 'game', 'match'],
    ['🎾', 'Tennis', 'match', 'court'],
    ['🏉', 'Rugby', 'match', 'game'],
    ['🏐', 'Volleyball', 'beach', 'game'],
    ['🏸', 'Badminton', 'game', 'racket'],
    ['🏓', 'Table tennis', 'ping pong', 'game'],
    ['🏒', 'Ice hockey', 'game', 'rink'],
    ['🥍', 'Lacrosse', 'game', 'match'],
    ['🏹', 'Archery', 'range', 'activity'],
    ['⛳', 'Golf', 'course', 'tee', 'round'],
    ['🎳', 'Bowling', 'game', 'alley'],
    ['🎯', 'Darts', 'pub', 'game'],
    ['🎱', 'Pool', 'billiards', 'snooker', 'bar', 'game'],
    ['🎮', 'Arcade', 'games', 'video games'],
    ['🕹', 'Retro arcade', 'games', 'joystick'],
    ['🎲', 'Board games', 'dice', 'games', 'night in'],
    ['♟', 'Chess', 'games', 'strategy'],
    ['🧩', 'Puzzle', 'escape room', 'games'],
    ['🥊', 'Boxing', 'fight', 'gym', 'match'],
    ['🥋', 'Martial arts', 'karate', 'judo', 'class'],
    ['🤺', 'Fencing', 'sport', 'class'],
    ['🧘', 'Yoga', 'meditation', 'wellness', 'pilates', 'stretch'],
    ['🏋', 'Gym', 'workout', 'fitness', 'weights'],
    ['🤸', 'Class', 'fitness', 'gymnastics', 'workout'],
    ['🏃', 'Running', 'jog', 'run', 'marathon'],
    ['🚶', 'Walk', 'stroll', 'wander', 'walking'],
    ['🧗‍♀️', 'Bouldering', 'climbing', 'gym'],
    ['🏟', 'Stadium', 'arena', 'match', 'game', 'concert'],
    ['🏆', 'Tournament', 'final', 'match', 'trophy'],
    ['🎽', 'Race', 'marathon', 'run', 'event'],
  ]),

  group('Wellness', [
    ['💆', 'Massage', 'spa', 'treatment', 'relax'],
    ['💅', 'Salon', 'nails', 'beauty', 'pamper'],
    ['💇', 'Haircut', 'barber', 'salon'],
    ['🧖', 'Sauna', 'spa', 'steam', 'hammam', 'onsen'],
    ['♨️', 'Hot spring', 'onsen', 'thermal', 'baths', 'spa'],
    ['🛁', 'Baths', 'spa', 'soak', 'thermal'],
    ['🚿', 'Freshen up', 'shower', 'hotel'],
    ['🕉', 'Meditation', 'mindfulness', 'retreat', 'quiet'],
    ['🪷', 'Retreat', 'lotus', 'calm', 'wellness'],
    ['😴', 'Rest', 'nap', 'sleep', 'downtime', 'lie in'],
    ['🛌', 'Lie in', 'sleep', 'rest', 'slow morning'],
    ['💤', 'Downtime', 'rest', 'sleep', 'free time'],
  ]),

  group('Landmarks', [
    ['🗼', 'Tower', 'landmark', 'eiffel', 'viewpoint'],
    ['🗽', 'Statue', 'landmark', 'monument', 'liberty'],
    ['🏰', 'Castle', 'palace', 'fortress', 'chateau'],
    ['🏯', 'Japanese castle', 'castle', 'japan', 'landmark'],
    ['⛩', 'Shrine', 'torii', 'temple', 'japan'],
    ['🛕', 'Temple', 'hindu', 'shrine', 'religious'],
    ['🕌', 'Mosque', 'religious', 'islamic'],
    ['⛪', 'Church', 'cathedral', 'chapel', 'religious', 'basilica'],
    ['🕍', 'Synagogue', 'religious', 'temple'],
    ['🕋', 'Pilgrimage', 'religious', 'holy site'],
    ['🌉', 'Bridge', 'landmark', 'crossing', 'viewpoint'],
    ['🌁', 'Viewpoint', 'lookout', 'panorama', 'fog'],
    ['🗾', 'Region', 'map', 'area', 'country'],
    ['🏗', 'Architecture', 'building', 'construction', 'modern'],
    ['🏙', 'Skyline', 'city', 'downtown', 'viewpoint'],
    ['🌆', 'Cityscape', 'city', 'dusk', 'skyline'],
    ['🏘', 'Old town', 'quarter', 'neighbourhood', 'historic'],
    ['⛲', 'Fountain', 'square', 'plaza', 'landmark'],
    ['🗻', 'Iconic peak', 'fuji', 'mountain', 'landmark'],
    ['🎇', 'Light show', 'sparkler', 'evening', 'display'],
    ['🚩', 'Landmark', 'flag', 'marker', 'point of interest'],
  ]),

  group('Nature', [
    ['🌅', 'Sunrise', 'dawn', 'early', 'morning'],
    ['🌄', 'Sunset', 'dusk', 'golden hour', 'evening'],
    ['🌇', 'Golden hour', 'sunset', 'dusk', 'evening'],
    ['🌌', 'Milky way', 'stars', 'night sky', 'astronomy'],
    ['🏞', 'National park', 'park', 'nature', 'landscape', 'valley'],
    ['🌲', 'Forest', 'woods', 'trees', 'trail'],
    ['🌳', 'Park', 'tree', 'green space', 'gardens'],
    ['🌴', 'Palm trees', 'tropical', 'beach', 'resort'],
    ['🌵', 'Desert', 'cactus', 'dunes', 'arid'],
    ['🏜', 'Dunes', 'desert', 'sand'],
    ['🌋', 'Volcano', 'crater', 'lava', 'hike'],
    ['🏕', 'Wilderness', 'camp', 'outdoors', 'nature'],
    ['🌿', 'Nature', 'green', 'plants', 'garden'],
    ['🍃', 'Gardens', 'leaves', 'park', 'botanical'],
    ['🌾', 'Countryside', 'fields', 'rural', 'farm'],
    ['🌷', 'Tulips', 'flowers', 'spring', 'gardens'],
    ['🌸', 'Blossom', 'cherry', 'sakura', 'spring', 'flowers'],
    ['🌺', 'Tropical flower', 'hibiscus', 'flowers', 'lei'],
    ['🌹', 'Roses', 'flowers', 'romantic', 'gardens'],
    ['🌻', 'Sunflowers', 'fields', 'flowers', 'summer'],
    ['🍁', 'Autumn', 'fall', 'leaves', 'foliage'],
    ['❄️', 'Snow', 'winter', 'cold', 'ice'],
    ['☀️', 'Sunny', 'weather', 'clear', 'hot'],
    ['⛅', 'Partly cloudy', 'weather'],
    ['🌦', 'Showers', 'weather', 'rain'],
    ['🌧', 'Rain', 'weather', 'wet'],
    ['⛈', 'Storm', 'weather', 'thunder'],
    ['🌪', 'Wind', 'weather', 'storm'],
    ['🌫', 'Fog', 'mist', 'weather', 'haze'],
    ['🌙', 'Night', 'evening', 'moon', 'late'],
    ['⭐', 'Stargazing', 'star', 'night', 'astronomy'],
    ['🌟', 'Special', 'star', 'highlight'],
    ['🌈', 'Rainbow', 'weather', 'colourful'],
    ['💧', 'Waterfall', 'water', 'river', 'spring'],
    ['🏔', 'Glacier', 'ice', 'mountain', 'snow'],
  ]),

  group('Animals', [
    ['🐋', 'Whale watching', 'whale', 'boat', 'wildlife'],
    ['🐬', 'Dolphins', 'wildlife', 'boat', 'sea'],
    ['🦭', 'Seals', 'wildlife', 'coast'],
    ['🐢', 'Turtles', 'wildlife', 'snorkel', 'reef'],
    ['🐠', 'Aquarium', 'fish', 'reef', 'snorkel'],
    ['🦈', 'Sharks', 'diving', 'aquarium', 'wildlife'],
    ['🐙', 'Octopus', 'sea life', 'aquarium'],
    ['🦁', 'Safari', 'wildlife', 'zoo', 'game drive', 'lion'],
    ['🐘', 'Elephants', 'safari', 'wildlife', 'sanctuary'],
    ['🦒', 'Giraffes', 'safari', 'zoo', 'wildlife'],
    ['🦓', 'Zebras', 'safari', 'wildlife'],
    ['🦏', 'Rhinos', 'safari', 'wildlife'],
    ['🐆', 'Big cats', 'safari', 'leopard', 'wildlife'],
    ['🐻', 'Bears', 'wildlife', 'national park'],
    ['🐼', 'Pandas', 'zoo', 'wildlife'],
    ['🦘', 'Kangaroos', 'wildlife', 'australia'],
    ['🐨', 'Koalas', 'wildlife', 'australia', 'zoo'],
    ['🦥', 'Sloths', 'wildlife', 'rainforest'],
    ['🐒', 'Monkeys', 'wildlife', 'jungle'],
    ['🐧', 'Penguins', 'wildlife', 'zoo', 'aquarium'],
    ['🦜', 'Birdwatching', 'birds', 'wildlife', 'parrot'],
    ['🦩', 'Flamingos', 'wildlife', 'birds', 'lagoon'],
    ['🦉', 'Owls', 'wildlife', 'birds', 'night'],
    ['🐎', 'Horses', 'riding', 'ranch', 'stables'],
    ['🐕', 'Dog friendly', 'pet', 'dog', 'walk'],
    ['🐈', 'Cats', 'pet', 'cat cafe'],
    ['🐑', 'Farm', 'sheep', 'countryside', 'animals'],
    ['🐄', 'Dairy farm', 'cows', 'countryside', 'farm'],
    ['🦌', 'Deer', 'wildlife', 'park', 'nara'],
    ['🐫', 'Camel ride', 'desert', 'camel', 'wildlife'],
    ['🦙', 'Llamas', 'wildlife', 'andes', 'farm'],
    ['🐝', 'Bees', 'honey', 'nature', 'farm'],
    ['🦋', 'Butterflies', 'nature', 'garden', 'wildlife'],
  ]),

  group('Travel', [
    ['✈️', 'Flight', 'plane', 'airport', 'fly', 'departure'],
    ['🛫', 'Departure', 'takeoff', 'flight', 'airport'],
    ['🛬', 'Arrival', 'landing', 'flight', 'airport'],
    ['🛩', 'Small plane', 'charter', 'scenic flight'],
    ['🛂', 'Passport control', 'immigration', 'customs', 'border'],
    ['🛃', 'Customs', 'border', 'declare'],
    ['🛄', 'Baggage claim', 'luggage', 'airport'],
    ['🧳', 'Luggage', 'bags', 'checkin', 'pack'],
    ['🚂', 'Train', 'rail', 'station', 'metro'],
    ['🚄', 'High-speed rail', 'train', 'bullet', 'shinkansen'],
    ['🚆', 'Rail journey', 'train', 'scenic'],
    ['🚇', 'Metro', 'subway', 'underground', 'tube'],
    ['🚊', 'Tram', 'streetcar', 'light rail'],
    ['🚋', 'Historic tram', 'streetcar', 'tram 28'],
    ['🚌', 'Bus', 'coach', 'shuttle'],
    ['🚐', 'Minivan', 'shuttle', 'transfer', 'van'],
    ['🚗', 'Drive', 'car', 'road trip', 'rental'],
    ['🚙', 'Road trip', 'car', 'suv', 'drive'],
    ['🚕', 'Taxi', 'cab', 'uber', 'ride'],
    ['🛺', 'Tuk-tuk', 'rickshaw', 'ride'],
    ['🏍', 'Motorbike', 'motorcycle', 'ride'],
    ['🛵', 'Scooter', 'moped', 'vespa', 'ride'],
    ['🚲', 'Bike', 'bicycle', 'cycle', 'rental'],
    ['🛴', 'E-scooter', 'scooter', 'ride', 'rental'],
    ['⛴', 'Ferry', 'boat', 'crossing', 'port'],
    ['🛳', 'Cruise', 'ship', 'boat', 'liner'],
    ['🚤', 'Speedboat', 'boat', 'charter'],
    ['🛥', 'Yacht', 'boat', 'charter', 'private'],
    ['🚁', 'Helicopter', 'scenic flight', 'transfer'],
    ['🚡', 'Cable car', 'gondola', 'funicular', 'lift'],
    ['🚠', 'Funicular', 'cable car', 'mountain', 'lift'],
    ['🚞', 'Mountain railway', 'scenic', 'train'],
    ['🅿️', 'Parking', 'car park', 'garage'],
    ['⛽', 'Fuel stop', 'gas', 'petrol', 'road trip'],
    ['🛣', 'Road', 'highway', 'drive', 'route'],
  ]),

  group('Stays', [
    ['🏨', 'Hotel', 'stay', 'accommodation', 'checkin'],
    ['🏩', 'Resort', 'hotel', 'stay', 'spa'],
    ['🏠', 'Rental', 'airbnb', 'house', 'apartment', 'stay'],
    ['🏡', 'Cottage', 'cabin', 'countryside', 'stay'],
    ['🛖', 'Cabin', 'hut', 'lodge', 'stay'],
    ['🏚', 'Guesthouse', 'hostel', 'pension', 'stay'],
    ['⛺', 'Campsite', 'tent', 'glamping', 'stay'],
    ['🛏', 'Check in', 'bed', 'hotel', 'room', 'stay'],
    ['🔑', 'Key pickup', 'checkin', 'keys', 'access'],
    ['🧹', 'Check out', 'leave', 'clean', 'hotel'],
    ['🛎', 'Front desk', 'concierge', 'reception', 'hotel'],
    ['🧼', 'Laundry', 'washing', 'chores'],
  ]),

  group('Practical', [
    ['🎟', 'Tickets', 'booking', 'entry', 'admission', 'reservation'],
    ['🎫', 'Booking', 'ticket', 'reservation', 'entry'],
    ['📅', 'Scheduled', 'calendar', 'date', 'booking'],
    ['🗓', 'Itinerary', 'calendar', 'plan', 'schedule'],
    ['⏰', 'Early start', 'alarm', 'wake up', 'time'],
    ['⏱', 'Timed entry', 'slot', 'timer', 'booking'],
    ['⌛', 'Free time', 'gap', 'flexible', 'downtime'],
    ['💰', 'Budget', 'money', 'cost', 'cash'],
    ['💳', 'Payment', 'card', 'pay', 'money'],
    ['🏧', 'Cash', 'atm', 'money', 'withdraw'],
    ['🧾', 'Receipt', 'bill', 'expenses', 'split'],
    ['💱', 'Currency', 'exchange', 'money', 'fx'],
    ['📱', 'SIM / data', 'phone', 'esim', 'wifi'],
    ['📶', 'Wifi', 'signal', 'internet', 'data'],
    ['🔌', 'Adapter', 'charger', 'plug', 'power'],
    ['🔋', 'Charge up', 'battery', 'power bank'],
    ['💊', 'Pharmacy', 'medicine', 'chemist', 'health'],
    ['🏥', 'Medical', 'hospital', 'doctor', 'clinic'],
    ['🩹', 'First aid', 'medical', 'health'],
    ['🧴', 'Sunscreen', 'toiletries', 'pharmacy', 'beach'],
    ['🧻', 'Supplies', 'essentials', 'shop'],
    ['☔', 'Rain plan', 'umbrella', 'weather', 'backup'],
    ['🧥', 'Layers', 'jacket', 'cold', 'pack'],
    ['👒', 'Sun hat', 'beach', 'pack'],
    ['📍', 'Meeting point', 'pin', 'location', 'meet', 'where'],
    ['📌', 'Placeholder', 'pin', 'todo', 'tbd', 'note'],
    ['📝', 'Notes', 'todo', 'list', 'write'],
    ['❓', 'To decide', 'tbd', 'unsure', 'question', 'maybe'],
    ['✅', 'Confirmed', 'booked', 'done', 'locked'],
    ['⚠️', 'Heads up', 'warning', 'caution', 'note'],
    ['🚫', 'Closed', 'not available', 'avoid'],
    ['♿', 'Accessible', 'accessibility', 'step free'],
    ['🚻', 'Restrooms', 'toilets', 'wc', 'bathroom'],
    ['🛗', 'Lift', 'elevator', 'accessible'],
    ['🅰️', 'Option A', 'choice', 'alternative'],
  ]),

  group('People', [
    ['👋', 'Meet up', 'hello', 'greet', 'rendezvous'],
    ['🤝', 'Meeting', 'handshake', 'business', 'intro'],
    ['👥', 'Group', 'together', 'everyone', 'people'],
    ['👯', 'Friends', 'group', 'together', 'crew'],
    ['👨‍👩‍👧', 'Family time', 'kids', 'family', 'group'],
    ['👶', 'Baby', 'infant', 'family'],
    ['🐣', 'Kid friendly', 'children', 'family', 'kids'],
    ['🧑‍🤝‍🧑', 'Together', 'couple', 'pair', 'friends'],
    ['💑', 'Date night', 'couple', 'romantic', 'dinner'],
    ['💍', 'Wedding', 'engagement', 'ceremony', 'anniversary'],
    ['👰', 'Bride', 'wedding', 'ceremony'],
    ['🤵', 'Groom', 'wedding', 'ceremony', 'black tie'],
    ['💒', 'Ceremony', 'wedding', 'chapel', 'venue'],
    ['🥳', 'Celebration', 'birthday', 'party', 'anniversary'],
    ['🎂', 'Birthday', 'cake', 'celebration'],
    ['🧑‍🏫', 'Guide', 'tour guide', 'lesson', 'class'],
    ['🕺', 'Night out', 'dancing', 'party'],
    ['🙋', 'Optional', 'whoever wants', 'volunteer'],
    ['🧑‍💻', 'Work block', 'laptop', 'remote', 'catch up'],
    ['💬', 'Catch up', 'chat', 'talk', 'discuss'],
  ]),

  group('Vibe', [
    ['✨', 'Vibe', 'special', 'magic', 'highlight'],
    ['❤️', 'Favourite', 'love', 'heart', 'must do'],
    ['💫', 'Highlight', 'special', 'memorable'],
    ['🔥', 'Must do', 'hot', 'top pick', 'unmissable'],
    ['⭐', 'Top pick', 'star', 'favourite', 'best'],
    ['🎊', 'Festival', 'event', 'celebration', 'parade'],
    ['🏳️‍🌈', 'Pride', 'lgbtq', 'parade', 'festival'],
    ['🤩', 'Excited', 'looking forward', 'hyped'],
    ['😌', 'Relaxed', 'easy', 'slow', 'chill'],
    ['🦋', 'Slow morning', 'gentle', 'easy', 'relaxed'],
    ['🥂', 'Toast', 'celebrate', 'cheers'],
    ['🎀', 'Treat', 'special', 'pamper'],
    ['🍀', 'Wildcard', 'luck', 'spontaneous', 'maybe'],
    ['🌞', 'Day plan', 'daytime', 'morning'],
    ['🌜', 'Evening plan', 'night', 'late'],
  ]),

  group('Flags', [
    ['🇵🇹', 'Portugal', 'lisbon', 'porto', 'flag'],
    ['🇪🇸', 'Spain', 'madrid', 'barcelona', 'flag'],
    ['🇫🇷', 'France', 'paris', 'nice', 'flag'],
    ['🇮🇹', 'Italy', 'rome', 'milan', 'venice', 'flag'],
    ['🇬🇷', 'Greece', 'athens', 'santorini', 'flag'],
    ['🇬🇧', 'UK', 'britain', 'london', 'england', 'flag'],
    ['🇮🇪', 'Ireland', 'dublin', 'flag'],
    ['🇳🇱', 'Netherlands', 'amsterdam', 'holland', 'flag'],
    ['🇧🇪', 'Belgium', 'brussels', 'bruges', 'flag'],
    ['🇩🇪', 'Germany', 'berlin', 'munich', 'flag'],
    ['🇦🇹', 'Austria', 'vienna', 'salzburg', 'flag'],
    ['🇨🇭', 'Switzerland', 'zurich', 'geneva', 'alps', 'flag'],
    ['🇨🇿', 'Czechia', 'prague', 'flag'],
    ['🇵🇱', 'Poland', 'krakow', 'warsaw', 'flag'],
    ['🇭🇺', 'Hungary', 'budapest', 'flag'],
    ['🇭🇷', 'Croatia', 'split', 'dubrovnik', 'flag'],
    ['🇸🇪', 'Sweden', 'stockholm', 'flag'],
    ['🇳🇴', 'Norway', 'oslo', 'fjords', 'flag'],
    ['🇩🇰', 'Denmark', 'copenhagen', 'flag'],
    ['🇫🇮', 'Finland', 'helsinki', 'flag'],
    ['🇮🇸', 'Iceland', 'reykjavik', 'flag'],
    ['🇹🇷', 'Türkiye', 'turkey', 'istanbul', 'flag'],
    ['🇲🇦', 'Morocco', 'marrakech', 'flag'],
    ['🇪🇬', 'Egypt', 'cairo', 'flag'],
    ['🇿🇦', 'South Africa', 'cape town', 'flag'],
    ['🇰🇪', 'Kenya', 'nairobi', 'safari', 'flag'],
    ['🇦🇪', 'UAE', 'dubai', 'abu dhabi', 'flag'],
    ['🇮🇳', 'India', 'delhi', 'mumbai', 'flag'],
    ['🇹🇭', 'Thailand', 'bangkok', 'phuket', 'flag'],
    ['🇻🇳', 'Vietnam', 'hanoi', 'saigon', 'flag'],
    ['🇸🇬', 'Singapore', 'flag'],
    ['🇮🇩', 'Indonesia', 'bali', 'jakarta', 'flag'],
    ['🇯🇵', 'Japan', 'tokyo', 'kyoto', 'osaka', 'flag'],
    ['🇰🇷', 'South Korea', 'seoul', 'flag'],
    ['🇨🇳', 'China', 'beijing', 'shanghai', 'flag'],
    ['🇹🇼', 'Taiwan', 'taipei', 'flag'],
    ['🇭🇰', 'Hong Kong', 'flag'],
    ['🇦🇺', 'Australia', 'sydney', 'melbourne', 'flag'],
    ['🇳🇿', 'New Zealand', 'auckland', 'queenstown', 'flag'],
    ['🇺🇸', 'USA', 'america', 'new york', 'flag'],
    ['🇨🇦', 'Canada', 'toronto', 'vancouver', 'flag'],
    ['🇲🇽', 'Mexico', 'cancun', 'mexico city', 'flag'],
    ['🇨🇷', 'Costa Rica', 'flag'],
    ['🇧🇷', 'Brazil', 'rio', 'sao paulo', 'flag'],
    ['🇦🇷', 'Argentina', 'buenos aires', 'flag'],
    ['🇨🇱', 'Chile', 'santiago', 'patagonia', 'flag'],
    ['🇵🇪', 'Peru', 'lima', 'machu picchu', 'flag'],
    ['🇨🇴', 'Colombia', 'bogota', 'medellin', 'flag'],
  ]),
]

/** Flat list — every emoji, in group order. */
export const SLOT_EMOJIS: SlotEmoji[] = SLOT_EMOJI_GROUPS.flatMap((g) => g.emojis)

/** Default emoji per category when no custom icon is set. */
export const CATEGORY_ICONS: Record<string, string> = {
  food: '🍽',
  activity: '🎭',
  travel: '✈️',
  accommodation: '🏨',
  vibe: '✨',
}

/** Does this entry match a lowercased search term? */
export function matchesEmoji(entry: SlotEmoji, groupName: string, q: string): boolean {
  if (entry.label.toLowerCase().includes(q)) return true
  if (groupName.toLowerCase().includes(q)) return true
  return (entry.keywords ?? []).some((k) => k.includes(q))
}
